export enum ExceptionCode {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  INVALID_EMAIL = 'INVALID_EMAIL',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  INVALID_NAME = 'INVALID_NAME',
  INVALID_ROLE = 'INVALID_ROLE',
  INVALID_ID = 'INVALID_ID'
}
